server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = /manifest.json {
        types { }
        default_type application/manifest+json;
    }

    location = /service-worker.js {
        add_header Cache-Control "no-cache";
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
